# Generated by Django 4.1.6 on 2023-02-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0002_alter_section_end_time_alter_section_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mujadwill.instructor'),
        ),
    ]
