# Generated by Django 4.1.6 on 2023-02-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0003_alter_section_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
    ]
