# Generated by Django 4.1.6 on 2023-02-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0004_remove_section_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('isAccepted', models.BooleanField()),
                ('conflict_fitness', models.IntegerField(default=0)),
                ('fullLoad_fitness', models.IntegerField(default=0)),
                ('fourDays_fitness', models.IntegerField(default=0)),
                ('fitness', models.IntegerField(default=0)),
            ],
        ),
    ]
