# Generated by Django 4.1.6 on 2023-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0005_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
