# Generated by Django 4.1.6 on 2023-02-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0006_alter_schedule_isaccepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='conflict_fitness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fitness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fourDays_fitness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fullLoad_fitness',
            field=models.FloatField(default=0),
        ),
    ]
