# Generated by Django 4.1.6 on 2023-02-12 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0007_alter_schedule_conflict_fitness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='theory_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mujadwill.section'),
        ),
    ]
