# Generated by Django 4.1.6 on 2023-02-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0011_alter_section_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
