# Generated by Django 4.1.6 on 2023-02-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0013_preffernce'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='secret_token',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preffernce',
            name='prefferd_subjects',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
    ]
