# Generated by Django 4.1.6 on 2023-02-14 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mujadwill', '0014_instructor_secret_token_preffernce_prefferd_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mujadwill.preffernce'),
        ),
    ]
